# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Weihong Xu | 徐炜鸿
# title: Your job title
email: xuweih0712@gmail.com
# phone: Your phone number (optional)
website: wh-xu.github.io

# Social links
#twitter_username: jekyllrb
github_username:  wh-xu
google_scholar_link: iKoPPOYAAAAJ
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: weihong-xu-555691124
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll

# About Section
about_title: About Me #(Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.
  I am currently a third-year MS student at the [Southeast University](https://www.seu.edu.cn/english). I work under supervision of [Prof. Chuan Zhang](https://www.researchgate.net/profile/Chuan_Zhang24) 
  and [Prof. Yair Be'ery](http://www.eng.tau.ac.il/~ybeery). I received B.E. degree in Information Engineering from the [Southeast University](https://www.seu.edu.cn/english) in 2017.

  My research interests include algorithm optimization in next-generation wireless systems (forward error-correction and massive MIMO detection) and design of efficient hardware architectures for 
  neuromorphic computing and 5G baseband processing. I am currently doing a research intern in [Intel Labs China](http://intel.com) where I develop flexible MIMO processor for 5G systems on FPGA.

  **Please check my** [<mark>CV.PDF</mark>](./cv/CV_weihong.pdf).

# Education Section
education_title: Education #(Use this to override about education section title)

# Experience Section
experience_title: Research Experience #(Use this to override about experience section title)

# Projects Section
projects_title: Projects #(Use this to override about projects section title)



more_title: Publications #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraph


  #### Algorithms and Architectures Optimization for Convolutional Neural Networks   

  [**Using Fermat Number Transform to Accelerate Convolutional Neural Network**](https://ieeexplore.ieee.org/document/8252655)   
  **Weihong Xu**, Xiaohu You, Chuan Zhang   
  *IEEE International Conference on ASIC (ASICON)*, Guiyang, China, 2017    
  [[**PDF**](./paper/asicon_2017.pdf)][[**Slides**](./slides/asicon_2017_slides.pdf)]

  [**Efficient Deep Convolutional Neural Networks Accelerator without Multiplication and Retraining**](https://ieeexplore.ieee.org/abstract/document/8461627)   
  **Weihong Xu**, Zaichen Zhang, Xiaohu You, Chuan Zhang   
  *IEEE International Conference on Acoustics, Speech and Signal Processing (ICASSP)*, Calgary, AB, Canada, 2018    
  [[**PDF**](./paper/icassp_2018.pdf)][[**Slides**](./slides/icassp_2018_slides.pdf)]

  **Reconfigurable and Low-Complexity Accelerator for Convolutional and Generative Networks over Finite Fields**   
  **Weihong Xu**, Zaichen Zhang, Xiaohu You, Chuan Zhang   
  Accepted by *IEEE Transactions on Computer-Aided Design of Integrated Circuits and Systems (TCAD)*, 2019    
  [[**PDF**](./paper/tcad_fnt_cnn_2019.pdf)]

  ***

  #### Deep Learning in Wireless Communications   

  [**Improved Polar Decoding based on Deep Learning**](https://ieeexplore.ieee.org/document/8109997)   
  **Weihong Xu**, Zhizhen Wu, Yeong-Luh Ueng, Xiaohu You, Chuan Zhang   
  *IEEE Workshop on Signal Processing Systems (SiPS)*, Lorient, France, 2017    
  [[**PDF**](./paper/sips_2017.pdf)]

  [**Joint Neural Network Equalizer and Decoder**](https://ieeexplore.ieee.org/document/8491056)   
  **Weihong Xu**, Xiaohu You, Chuan Zhang, Yair Be'ery   
  *The 15th International Symposium on Wireless Communication Systems (ISWCS)*, Lisbon, Portugal, 2018    
  [[**PDF**](./paper/iswcs_2018.pdf)][[**Slides**](./slides/iswcs_2018_slides.pdf)]

  [**Polar Decoding on Sparse Graphs with Deep Learning**](https://ieeexplore.ieee.org/document/8645372)   
  **Weihong Xu**, Xiaohu You, Chuan Zhang, Yair Be'ery   
  *The 52nd Asilomar Conference on Signals, Systems, and Computers*, Pacific Grove, California, USA, 2018    
  [[**PDF**](./paper/asilomar_2018.pdf)][[**Slides**](./slides/asilomar_2018_slides.pdf)]

  **On the Efficient Design of Neural Networks in Communication Systems**   
  **Weihong Xu**, Xiaosi Tan, Xiaohu You, Chuan Zhang, Yair Be'ery   
  To appear in *the 53rd Asilomar Conference on Signals, Systems, and Computers*, Pacific Grove, California, USA, 2019    
  [[**PDF**](./paper/asilomar_2019.pdf)]

  ***


  #### Massive MIMO Systems   

  **Deep Learning-aided Belief Propagation Decoder for Polar Codes**   
  **Weihong Xu**, Xiaosi Tan, Yair Be’ery, Zaichen Zhang, Xiaohu You, Chuan Zhang     
  Submitted to *IEEE Transactions on Vehicular Technology (TVT)*, 2019    
  [[**PDF**](./paper/polar_tvt_2019.pdf)]

  **Efficient Expectation Propagation Massive MIMO Detector with Neumann-Series Approximation**   
  Xiaosi Tan, **Weihong Xu**, Yaping Zhang, Zaichen Zhang, Xiaohu You, Chuan Zhang   
  To appear in *IEEE Transactions on Circuits and Systems II: Express Briefs*, 2019    
  [[**PDF**](./paper/tcas2_2019.pdf)]

  **Improving Massive MIMO Message Passing Detectors with Deep Neural Network**   
  Xiaosi Tan, **Weihong Xu**, Kai Sun, Yunhao Xu, Yair Be'ery, Zaichen Zhang, Xiaohu You, Chuan Zhang   
  Submitted to *IEEE Transactions on Vehicular Technology (TVT)*, 2019    

  

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
